services:
  download-bot:
    image: download-bot:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: download-bot
    restart: unless-stopped
    # dns:
    #   - 1.1.1.1
    #   - 8.8.8.8
    # sysctls:
    #   - net.ipv6.conf.all.disable_ipv6=1
    #   - net.ipv6.conf.default.disable_ipv6=1
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      HTTPS_PROXY: ${HTTPS_PROXY}
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ./www.youtube.com_cookies.txt:/app/www.youtube.com_cookies.txt
networks:
  default:
    driver: host
    driver_opts:
      com.docker.network.driver.mtu: "1400"